runtime: custom
env: flex
# entrypoint: gunicorn -b :$PORT app:app

# runtime_config:
#   python_version: 3

# For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
resources:
  cpu: 1
  memory_gb: 4.0
  disk_size_gb: 10